---
# This Docker composition file is used to build and test the container

name: saver

secrets:
  aws_config:
    file: ./src/secrets/aws_config
  scan_write_creds:
    file: ./src/secrets/scan_write_creds.yml

services:
  redis:
    image: redis:alpine

  saver:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      # Setting this environment variable ensures that the config file
      # (and not just any credentials file that is present) is loaded.
      - AWS_SDK_LOAD_CONFIG=1
      # This is a placeholder suitable only for local testing.
      - ELASTICSEARCH_URL=https://search-example.us-east-1.es.amazonaws.com
    image: cisagov/saver
    init: true
    restart: "no"
    secrets:
      - source: aws_config
        target: aws_config
      - source: scan_write_creds
        target: scan_write_creds.yml
